package UserInterface;

import Business.Business;
import Business.ConfigureBusiness;
import Business.SalesPerson;
import Business.Supplier;
import Business.UserAccount;
import UserInterface.AdminstrativeRole.AdminWorkAreaJPanel;
import UserInterface.SalesPersonRole.SalesPersonWorkAreaJPanel;
import UserInterface.SupplierRole.SupplierWorkAreaJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mihir Mehta / Hechen Gao
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Business business;

    public MainJFrame() {
        initComponents();
        //supplierDirectory = new SupplierDirectory();
        setSize(1000, 800);
        business = ConfigureBusiness.InitializeBusiness();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        loginBtn = new javax.swing.JButton();
        passwordTxtField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        usernameTxtField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setDividerLocation(150);

        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Password");

        jLabel1.setText("UserName");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usernameTxtField)
                            .addComponent(passwordTxtField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 83, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loginBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(logoutBtn)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernameTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(loginBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoutBtn)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(jPanel1);

        userProcessContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(userProcessContainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        loginBtn.setEnabled(true);
        logoutBtn.setEnabled(false);
        usernameTxtField.setEnabled(true);
        passwordTxtField.setEnabled(true);

        usernameTxtField.setText("");
        passwordTxtField.setText("");

        userProcessContainer.removeAll();
        JPanel blank = new JPanel();
        userProcessContainer.add("blank", blank);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed

        String userName = usernameTxtField.getText();
        String password = String.valueOf(passwordTxtField.getPassword());
        boolean flag = false;
        for (UserAccount ua : business.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getUserName().equals(userName) && ua.getPassword().equals(password)) {
                if (ua.getRole().equalsIgnoreCase(UserAccount.ADMIN)) {
                    userProcessContainer.removeAll();
                    AdminWorkAreaJPanel panel = new AdminWorkAreaJPanel(userProcessContainer, business);
                    userProcessContainer.add("admin", panel);
                    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                    layout.next(userProcessContainer);
                    flag = true;
                    break;
                } 
                else if (ua.getRole().equalsIgnoreCase(UserAccount.SALESPERSON)) {
                    userProcessContainer.removeAll();
                    for (SalesPerson sp : business.getSalesPersonDirectory().getSalesPersonList()) {
                        String name = sp.getFname();
                        if (ua.getPerson().getFname().equals(name)) {
                            SalesPersonWorkAreaJPanel panel = new SalesPersonWorkAreaJPanel(userProcessContainer, sp, business);
                            userProcessContainer.add("salesperson", panel);
                            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                            layout.next(userProcessContainer);
                            flag = true;
                            break;
                        }
                    }
                } 
                else if (ua.getRole().equalsIgnoreCase(UserAccount.SUPPLIER)) {
                    userProcessContainer.removeAll();
                    for(Supplier s : business.getSupplierDirectory().getSupplierlist()){
                        String name = s.getFname();
                        if(ua.getPerson().getFname().equals(name)){
                            SupplierWorkAreaJPanel panel = new SupplierWorkAreaJPanel(userProcessContainer, s, business);
                            userProcessContainer.add("supplier", panel);
                            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
                            layout.next(userProcessContainer);
                            flag = true;
                            break;
                        }
                    }
                }
            }
        }
        if (flag = false) {
            JOptionPane.showMessageDialog(null, "Incorrect username, password combination!");
            return;
        }
        loginBtn.setEnabled(false);
        logoutBtn.setEnabled(true);
        usernameTxtField.setEnabled(false);
        passwordTxtField.setEnabled(false);
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPasswordField passwordTxtField;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JTextField usernameTxtField;
    // End of variables declaration//GEN-END:variables

}
