package UserInterface.AdminstrativeRole;

import Business.Business;
import Business.SupplierDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;


public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Business business;

    public AdminWorkAreaJPanel(JPanel userProcessContainer, Business business) {

        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReport = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnManageSalesPerson = new javax.swing.JButton();
        btnManageSuppliers2 = new javax.swing.JButton();
        btnManageCustomers1 = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReport.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnReport.setText("Report >>");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });
        add(btnReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 260, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/AdminstrativeRole/Xerox.png"))); // NOI18N
        jLabel1.setText("XEROX - Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 460, 50));

        btnManageSalesPerson.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageSalesPerson.setText("Manage SalesPerson >>");
        btnManageSalesPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSalesPersonActionPerformed(evt);
            }
        });
        add(btnManageSalesPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 260, -1));

        btnManageSuppliers2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageSuppliers2.setText("Manage Suppliers >>");
        btnManageSuppliers2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSuppliers2ActionPerformed(evt);
            }
        });
        add(btnManageSuppliers2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 260, -1));

        btnManageCustomers1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnManageCustomers1.setText("Manage Customers >>");
        btnManageCustomers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCustomers1ActionPerformed(evt);
            }
        });
        add(btnManageCustomers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        ReportJPanel panel = new ReportJPanel(userProcessContainer, business);
        userProcessContainer.add("Report", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnManageSalesPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSalesPersonActionPerformed
        ManageSalesPerson panel = new ManageSalesPerson(userProcessContainer, business);
        userProcessContainer.add("ManageSalesPerson", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSalesPersonActionPerformed

    private void btnManageSuppliers2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSuppliers2ActionPerformed
        ManageSuppliers panel = new ManageSuppliers(userProcessContainer, business);
        userProcessContainer.add("ManageSuppliers", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageSuppliers2ActionPerformed

    private void btnManageCustomers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCustomers1ActionPerformed
        ManageCustomers panel = new ManageCustomers(userProcessContainer, business);
        userProcessContainer.add("ManageSupplierAdministrative", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageCustomers1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageCustomers1;
    private javax.swing.JButton btnManageSalesPerson;
    private javax.swing.JButton btnManageSuppliers2;
    private javax.swing.JButton btnReport;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
